"""
Distance metrics and comparison functions for SR models.

This module contains distance calculation functions that have been moved from
SRmodellib.py for better code organization and maintainability.

Functions moved here:
- ks_test: Kolmogorov-Smirnov test between distributions
- trim_to_range: Utility for trimming data to time ranges
- baysianDistance: Deprecated Bayesian distance (use baysian_dirichlet_distance)
- baysian_dirichlet_distance: Primary Bayesian distance method
- distance: Main distance function with multiple metrics

Note: baysianDistance2 has been removed as it was redundant.
"""

import numpy as np
from scipy.stats import ks_2samp, entropy
from scipy.special import gammaln
from .life_table import Life_table


def ks_test(distributions1, distributions2, bins, metric ='test_stat', trim=0,full=False):
    #returns the ks test statistic and p-value between two distributions
    #metric can be 'test_stat', 'p_value', mse or KL_divergence
    #trim is the number of bins to ignore at the begining of the distribution
    n = len(distributions1)
    distances = np.zeros(n)
    dx = bins[1]-bins[0]
    for i, key in enumerate(distributions1.keys()):
        dist1 = distributions1[key][trim:]
        dist2 = distributions2[key][trim:]
        dist1 = dist1/np.sum(dist1*dx)
        dist2 = dist2/np.sum(dist2*dx)
        ks = ks_2samp(dist1, dist2)
        if metric == 'test_stat':
            distances[i] = ks.statistic
        elif metric == 'p_value':
            distances[i] = 1-ks.pvalue
        elif metric == 'mse':
            # print(key,':',np.mean((dist1-dist2)**2))
            distances[i] = np.mean((dist1-dist2)**2)
        elif metric == 'KL_divergence':
            distances[i] = entropy(dist1,dist2)
        else:
            raise ValueError('metric should be test_stat or p_value')
    if full:
        return distances
    return np.sqrt(np.sum(distances)/n)
    
def trim_to_range(t,vals,time_range,renormalize_survival = False):
    #trims the values to the time range
    i_start = np.abs(t - time_range[0]).argmin()
    i_end = np.abs(t - time_range[1]).argmin()
    if renormalize_survival:
        vals = vals/vals[i_start]
    return t[i_start:i_end], vals[i_start:i_end]


def baysianDistance(sr1, sr2, time_range=None, dt=1, debug=False):
    """
    Calculate the likelihood that the death times of sr1 are generated by sr2.
    convention is that sr1 is the data and sr2 is the simulation
    
    DEPRECATED: This function is deprecated. Use baysian_dirichlet_distance instead.
    """
    import warnings
    warnings.warn(
        "baysianDistance is deprecated and will be removed in a future version. "
        "Use baysian_dirichlet_distance instead.",
        DeprecationWarning,
        stacklevel=2
    )
    
    from statsmodels.nonparametric.kernel_density import KDEMultivariate
    
    #if number of deathtimes is too small that causes issues and anyways not probable as a legitimate parameter set                                             
    if len(sr2.getDeathTimes()) <= 5:
        return -np.inf
    
    death_times2 = sr2.getDeathTimes()
    events2 = sr2.events
    #if time range is not None, use only deathtimes withtin the time range
    if time_range is not None:
        events2 = events2[(death_times2 >= time_range[0]) & (death_times2 <= time_range[1])]                                                                    
        death_times2 = death_times2[(death_times2 >= time_range[0]) & (death_times2 <= time_range[1])]                                                          
    #check that there are enough events to calculate the likelihood meaningfully
    if np.sum(events2) <= 5:
        return -np.inf
    
    death_times2 = death_times2[events2==1] #only those who died
    #this would be a smooth distribution generatated from sr2(simulation) to sample sr1(data) from                                                              
    kde = KDEMultivariate(death_times2, var_type='c', bw='normal_reference')
    

    events = sr1.events
    death_times = sr1.getDeathTimes()
    dts =sr1.properties.get('dt',np.ones_like(death_times)*dt)
    if time_range is not None:
        events = events[(death_times >= time_range[0]) & (death_times <= time_range[1])]                                                                        
        dts = dts[(death_times >= time_range[0]) & (death_times <= time_range[1])]                                                                              
        death_times = death_times[(death_times >= time_range[0]) & (death_times <= time_range[1])]                                                              
    died = death_times[events==1]
    censored = death_times[events==0]
    ndied = len(died)
    p_death_before_t_end =np.sum(events2)/len(events2)
    
    
    #creating the list of times we need to evalutate the kde at. This is all the death times + all the death times - the relevant dt                            
    # Creating the list of times we need to evaluate the kde at.
    # This includes all the death times and all the death times minus the relevant dt.                                                                          
    evaluation_times = np.concatenate((death_times, death_times - dts))
    evaluation_times = evaluation_times[(evaluation_times >= 0) & (evaluation_times <= max(death_times))]                                                       
    evaluation_times = np.unique(evaluation_times)

    #this piece of code is to accelerate the loglikelihood calculation
    times = evaluation_times
    log_pdt = kde.cdf(times) #the log integral of the probability density function on the time grid                                                             
    log_pdt = np.log(log_pdt[1:]-log_pdt[:-1])
    #insert a 0 at the beginning of the log_pdt array to make it the same length as times                                                                       
    log_pdt = np.insert(log_pdt, 0, 0)
    

    #if logp has nan values then try again then raise an error to debug
    if np.any(np.isnan(log_pdt)):
        if debug:
            print('log_pdt has nan values')
        return np.NaN

    logcdf = np.log(1-kde.cdf(times)) 
    #for every time in death times, find the nearst index in times and get the logp                                                                             
    logps = 0
    logps_censored = 0
    for t in died:
        idx = np.argmin(np.abs(times-t))
        logps+=(log_pdt[idx])
        if debug:
            if log_pdt[idx] == -np.inf or np.isnan(log_pdt[idx]):
                print(f'log_pdt[{idx}] is {log_pdt[idx]}')

    for t in censored:
        idx = np.argmin(np.abs(times-t))
        logps_censored+=(logcdf[idx])

    #the liklihod given by the kde is L= p(t_death=x_i)|died before t_end) so to correct we need to multiply by the number of ndied/n                           
    #in the loglikelihood this gives a term of ndied*np.log(p_death_before_t_end)                                                                               
    sums = logps+ndied*np.log(p_death_before_t_end) +logps_censored
    #check if sums is nan if so then raise an error to debug.
    if np.isnan(sums):
        print('ndied:',ndied)
        print('p_death_before_t_end:',p_death_before_t_end)
        print('logps:',logps)
        print('censored:',censored)
        print('censored_logLiklihood(censored):',logps_censored)
        raise ValueError('sums is nan')
    if debug:
        print('ndied:',ndied)
        print('p_death_before_t_end:',p_death_before_t_end)
        print('logps:',logps)
        print('censored:',censored)
        print('censored_logLiklihood(censored):',logps_censored)
        print('sums:',sums)
    return sums


def baysian_dirichlet_distance(sr1, sr2, time_range=None, dt=1, debug=False, lambda_smooth=0.5, sr_bins=None, alpha0=None):
    """
    Calculate the Dirichlet-multinomial likelihood that the death times of sr1 are generated by sr2.
    
    This function uses a Dirichlet-multinomial model to compute the log-likelihood.
    Convention: sr1 is the data, sr2 is the simulation.
    
    The likelihood is computed using the Dirichlet-multinomial formula:
        log L = gammaln(A0) - gammaln(m + A0) + sum(gammaln(y + alpha) - gammaln(alpha))
    
    where:
        - If alpha0 is None (default): alpha = c + lambda_smooth, A0 = sum(alpha)
        - If alpha0 is provided: alpha = alpha0 * q_hat, A0 = alpha0 (fixed)
        - c = counts from simulation
        - q_hat = smoothed proportions from simulation (c + lambda_smooth) / sum(c + lambda_smooth)
        - y = counts from data
        - m = sum(y) (total data observations)
    
    For censored data, we add:
        log L_cens = sum over bins r [gammaln(A[r] + L[r]) - gammaln(A[r])
                                      - gammaln(A0 + T_after + L[r]) + gammaln(A0 + T_after)]
    where:
        - A[r] = sum_{i>=r} alpha_prime[i] (tail cumulative sum)
        - L[r] = number of right-censored observations with censoring time in bin r
        - T_after = cumulative count of censored after bin r
        - alpha_prime = alpha + y (posterior parameters)
    
    Parameters:
    -----------
    sr1 : SR object or Life_table
        The data object (observations or life table)
    sr2 : SR object
        The simulation SR object (model to evaluate)
    time_range : tuple, optional
        Time range (min, max) to restrict analysis
    dt : float or array-like
        If scalar: bin size for creating histogram bins
        If array: explicit bin edges to use
    debug : bool
        If True, print debugging information
    lambda_smooth : float
        Smoothing parameter (Jeffreys prior uses 0.5, Laplace uses 1.0)
    sr_bins : object, optional
        Optional SR or Life_table used only to define bin edges when dt is scalar.
        Useful for debugging to freeze edges across runs. Has no effect if dt is an
        explicit array of edges or when sr1 is a Life_table (which supplies edges).
    alpha0 : float, optional
        Fixed concentration parameter for the Dirichlet prior. If provided, removes
        dependency on the number of deaths in the simulation by fixing A0 = alpha0
        and computing alpha = alpha0 * q_hat where q_hat are the smoothed proportions
        from the simulation. If None (default), uses the original behavior where
        alpha = c + lambda_smooth and A0 = sum(alpha).
    
    Returns:
    --------
    float
        Log-likelihood of the data under the Dirichlet-multinomial model
    """
    from statsmodels.nonparametric.kernel_density import KDEMultivariate
    
    # Check if sr1 is a Life_table
    is_life_table = isinstance(sr1, Life_table)
    
    if is_life_table:
        # Use life table's ages as bin edges
        bins = sr1.ages.copy()
        
        # Filter bins to time_range if provided
        if time_range is not None:
            mask_bins = (bins >= time_range[0]) & (bins <= time_range[1])
            bins = bins[mask_bins]
            if len(bins) < 2:
                return -np.inf
        
        # Extract death counts from life table: y_i = n_alive[i] - n_alive[i+1]
        y_bins = []
        for i in range(len(bins) - 1):
            # Find indices in original sr1.n_alive
            idx_i = np.where(sr1.ages == bins[i])[0][0]
            idx_ip1 = np.where(sr1.ages == bins[i+1])[0][0]
            y_bins.append(sr1.n_alive[idx_i] - sr1.n_alive[idx_ip1])
        
        y = np.array(y_bins)
        m = np.sum(y)  # Total deaths (not censored)
        
        # Handle censored data from tail_bin
        if sr1.tail_bin is not None:
            # Find if tail_bin age is within range
            tail_age = sr1.tail_bin['age']
            if time_range is None or (tail_age >= time_range[0] and tail_age <= time_range[1]):
                # All n_alive at last age are right-censored
                idx_last = np.where(sr1.ages == bins[-1])[0][0]
                censored1 = np.full(int(sr1.n_alive[idx_last]), bins[-1])  # All censored at last bin edge
            else:
                censored1 = np.array([])
        else:
            censored1 = np.array([])
        
        died1 = np.array([])  # No individual death times from life table
        events1 = np.array([])
        
    else:
        # Regular dataset path - existing logic
        # Get death times and events for sr1 (data)
        death_times1 = sr1.getDeathTimes()
        events1 = sr1.events
        
        # Restrict to time_range if provided
        if time_range is not None:
            mask1 = (death_times1 >= time_range[0]) & (death_times1 <= time_range[1])
            events1 = events1[mask1]
            death_times1 = death_times1[mask1]
        
        died1 = death_times1[events1 == 1]
        censored1 = death_times1[events1 == 0]
        m = len(died1)
    
    # Get death times and events for sr2 (simulation) - SAME FOR BOTH PATHS
    death_times2 = sr2.getDeathTimes()
    events2 = sr2.events
    
    # Restrict to time_range if provided
    if time_range is not None:
        mask2 = (death_times2 >= time_range[0]) & (death_times2 <= time_range[1])
        events2 = events2[mask2]
        death_times2 = death_times2[mask2]
    
    # Check if we have enough data from simulation
    if len(death_times2) <= 5:
        return -np.inf
    
    # ============================================================================
    # Step 1: Define bins
    # ============================================================================
    if is_life_table:
        # For Life_table, bins are already defined above
        if debug:
            print(f"Using life table ages as bins: {bins}")
    else:
        # If dt is an array, use it as bin edges directly
        if isinstance(dt, (list, tuple, np.ndarray)):
            bins = np.array(dt)
            if time_range is not None:
                # ensure edges cover [t1,t2]
                t1, t2 = time_range
                bins = bins[(bins >= t1) & (bins <= t2)]
                if bins[0] != t1:
                    bins = np.insert(bins, 0, t1)
                if bins[-1] != t2:
                    bins = np.append(bins, t2)
            if debug:
                print(f"Using provided bin edges: {bins}")
        else:
            # dt is a scalar - create bins with this bin size
            if time_range is not None:
                min_time = time_range[0]
                max_time = time_range[1]
            else:
                min_time = 0
                # Prefer sr_bins if provided to set a reproducible max
                if sr_bins is not None:
                    try:
                        if isinstance(sr_bins, Life_table):
                            max_time = sr_bins.getMaxLifetime()
                        else:
                            dt_bins = sr_bins.getDeathTimes()
                            max_time = np.max(dt_bins) if len(dt_bins) > 0 else 0
                    except Exception:
                        dt_bins = getattr(sr_bins, 'death_times', np.array([]))
                        max_time = np.max(dt_bins) if len(dt_bins) > 0 else 0
                else:
                    max_time = np.max(death_times1) if 'death_times1' in locals() and len(death_times1) > 0 else 0

            bins = np.arange(min_time, max_time + dt, dt)
            if time_range is not None and bins[-1] != max_time:
                bins = np.append(bins, max_time)
            if debug:
                print(f"Created bins from {min_time} to {max_time} with dt={dt}")
                print(f"Bins: {bins}")
    
    # The tail threshold T is the last bin edge
    # Everything >= T goes into the overflow bin
    T = bins[-1]
    
    # ============================================================================
    # Step 2: Compute counts in bins for simulation data (sr2)
    # ============================================================================
    # For non-censored (events2 == 1), histogram their death times
    died2 = death_times2[events2 == 1]
    
    # Use numpy histogram to count deaths in bins [edge_i, edge_{i+1})
    c_bins, _ = np.histogram(died2, bins=bins)
    
    # Count deaths in the tail (overflow bin): deaths >= T
    # OPTIMIZATION 1: Avoid unnecessary array copies when time_range is provided
    # Use already filtered data instead of creating full copies
    if time_range is not None:
        c_tail = np.sum((events2 == 1) & (death_times2 >= T))
    else:
        c_tail = np.sum(died2 >= T)
    
    # The total number of bins is len(bins) (including the overflow bin)
    # We fold the tail count into the last bin
    # c_bins has length len(bins)-1. We need to add the overflow bin.
    # According to pseudocode: fold tail into last bin
    if len(c_bins) > 0:
        # Overflow bin gets count from c_tail
        # c_bins has length len(bins)-1, we add c_tail as a separate overflow bin
        # to create final array of length len(bins)
        c = np.concatenate([c_bins, [c_tail]])
    else:
        c = np.array([c_tail])
    
    # Total number of non-censored events in simulation
    n_sim = len(died2)
    
    if debug:
        print(f"Simulation counts in bins (c): {c}")
        print(f"Total simulation events (n_sim): {n_sim}")
    
    # ============================================================================
    # Step 3: Compute counts in bins for data (sr1)
    # ============================================================================
    if is_life_table:
        # For Life_table, y is already computed above from n_alive differences
        # Append explicit tail as zero deaths; censor remaining alive at T handled below
        y = np.concatenate([y, np.array([0])])
        # m already set in life-table branch
    else:
        # For regular datasets, histogram death times into finite bins and add explicit tail
        y_bins, _ = np.histogram(died1, bins=bins)
        y_tail = np.sum(died1 >= T)

        y = np.concatenate([y_bins, [y_tail]])
        m = len(died1)  # Total number of non-censored events in data
    
    if debug:
        print(f"Data counts in bins (y): {y}")
        print(f"Total data events (m): {m}")
    
    # ============================================================================
    # Step 4: Compute Dirichlet-multinomial likelihood for non-censored data
    # ============================================================================
    # alpha = c + lambda_smooth
    
    
    

    if alpha0 is not None:
        counts = c + lambda_smooth
        q_hat  = counts / counts.sum()          # smoothed proportions in the bins
        A0     = alpha0                         # <- fixed across all evaluations
        alpha  = A0 * q_hat
    else:
        alpha = c + lambda_smooth
        A0 = np.sum(alpha)
    # Dirichlet-multinomial log-likelihood formula:
    # log L = gammaln(A0) - gammaln(m + A0) + sum(gammaln(y + alpha) - gammaln(alpha))
    
    if debug:
        # Calculate per-bin contributions for debugging only
        bin_contributions = gammaln(y + alpha) - gammaln(alpha)
        logL_uncensored = (gammaln(A0) - gammaln(m + A0) + np.sum(bin_contributions))
        
        print(f"alpha = c + lambda: {alpha}")
        print(f"A0 = sum(alpha): {A0}")
        print(f"\nUncensored data - Per-bin contributions to log-likelihood:")
        print(f"{'Bin':<6} {'y[i]':<8} {'c[i]':<8} {'alpha[i]':<10} {'Contribution':<15}")
        print("-" * 60)
        for i in range(len(bin_contributions)):
            print(f"{i:<6} {y[i]:<8.1f} {c[i]:<8.1f} {alpha[i]:<10.2f} {bin_contributions[i]:<15.6f}")
        print(f"\nConstant terms: gammaln(A0) - gammaln(m + A0) = {gammaln(A0) - gammaln(m + A0):.6f}")
        print(f"Sum of bin contributions: {np.sum(bin_contributions):.6f}")
        print(f"Log-likelihood (uncensored): {logL_uncensored}")
    else:
        # Fast path when debug is False - no intermediate arrays
        logL_uncensored = (gammaln(A0) - gammaln(m + A0) + 
                          np.sum(gammaln(y + alpha) - gammaln(alpha)))
    
    # ============================================================================
    # Step 5: Handle censored data
    # ============================================================================
    # Censored observations: events1 == 0 (or tail_bin for Life_table)
    # censored1 is already computed above for both Life_table and regular datasets
    
    if len(censored1) > 0:
        # Compute alpha_prime = alpha + y (posterior parameters)
        alpha_prime = alpha + y
        alpha0_prime = np.sum(alpha_prime)
        
        # Compute tail cumulative sums: A[r] = sum_{i>=r} alpha_prime[i]
        # A[r] is the sum of alpha_prime from bin r to the last bin (inclusive)
        K = len(alpha_prime)  # Number of bins
        A = np.zeros(K)
        for r in range(K):
            A[r] = np.sum(alpha_prime[r:])
        
        # Compute L[r]: right-censored mapping to the next bin (+1) and tail
        L = np.zeros(K)
        cens = np.asarray(censored1)
        if cens.size > 0:
            # Tail censored: c >= T
            L[K - 1] += np.sum(cens >= T)
            # Finite censored: c in [bins[r], bins[r+1)) contributes to L[r+1]
            finite_mask = cens < T
            if np.any(finite_mask):
                idx = np.searchsorted(bins, cens[finite_mask], side='right') - 1
                # Shift by +1
                for r in (idx + 1):
                    if 0 <= r < K:
                        L[r] += 1
        
        # Compute censored likelihood contribution
        # Iterate from K down to 1 (in Python: from K-1 down to 0)
        logL_censored = 0.0
        T_after = 0  # Cumulative count of censored observations after current bin
        
        if debug:
            print(f"\nCensored counts by bin (L): {L}")
            print(f"alpha_prime = alpha + y: {alpha_prime}")
            print(f"alpha0_prime = sum(alpha_prime): {alpha0_prime}")
            print(f"Tail cumulative sums A: {A}")
            print(f"\nCensored data - Per-bin contributions to log-likelihood:")
            print(f"{'Bin':<6} {'L[r]':<8} {'A[r]':<12} {'T_after':<10} {'Contribution':<15}")
            print("-" * 65)
            
            # Debug path: calculate and display per-bin contributions
            for r in range(K - 1, -1, -1):  # From K-1 down to 0
                Lr = L[r]
                if Lr == 0:
                    continue
                
                # Add censored contribution for bin r:
                # log L += gammaln(A[r] + Lr) - gammaln(A[r])
                #          - gammaln(alpha0_prime + T_after + Lr) + gammaln(alpha0_prime + T_after)
                bin_contrib = (gammaln(A[r] + Lr) - gammaln(A[r]) -
                              gammaln(alpha0_prime + T_after + Lr) + 
                              gammaln(alpha0_prime + T_after))
                
                print(f"{r:<6} {Lr:<8.1f} {A[r]:<12.2f} {T_after:<10.1f} {bin_contrib:<15.6f}")
                
                logL_censored += bin_contrib
                T_after += Lr
            
            print(f"\nLog-likelihood (censored): {logL_censored}")
        else:
            # Fast path when debug is False
            for r in range(K - 1, -1, -1):  # From K-1 down to 0
                Lr = L[r]
                if Lr == 0:
                    continue
                
                # Add censored contribution for bin r:
                # log L += gammaln(A[r] + Lr) - gammaln(A[r])
                #          - gammaln(alpha0_prime + T_after + Lr) + gammaln(alpha0_prime + T_after)
                logL_censored += (gammaln(A[r] + Lr) - gammaln(A[r]) -
                                 gammaln(alpha0_prime + T_after + Lr) + 
                                 gammaln(alpha0_prime + T_after))
                
                T_after += Lr
    else:
        logL_censored = 0.0
        if debug:
            print("No censored observations")
    
    # ============================================================================
    # Step 6: Total log-likelihood
    # ============================================================================
    total_logL = logL_uncensored + logL_censored
    
    if debug:
        print(f"\n{'='*65}")
        print(f"SUMMARY OF LOG-LIKELIHOOD CONTRIBUTIONS:")
        print(f"{'='*65}")
        print(f"Uncensored contribution:  {logL_uncensored:>15.6f}")
        print(f"Censored contribution:    {logL_censored:>15.6f}")
        print(f"{'-'*65}")
        print(f"Total log-likelihood:     {total_logL:>15.6f}")
        print(f"{'='*65}\n")
    
    # Check for NaN
    if np.isnan(total_logL):
        if debug:
            print("Warning: total log-likelihood is NaN")
        return -np.inf
    
    return total_logL


def distance(sr1, sr2, metric='dirichlet',time_range = None,**kwargs):
    """
    Calculate the distance between two SR models or SR model and equivalent data object according to different metrics.
    """
    if metric == 'survival':
        #calculate the mse between the two survival curves
        t1,s1 = sr1.getSurvival()
        t1,s1 = trim_to_range(t1,s1,time_range,renormalize_survival=True) if time_range is not None else (t1,s1)
        t2,s2 = sr2.getSurvival()
        t2,s2 = trim_to_range(t2,s2,time_range,renormalize_survival=True) if time_range is not None else (t2,s2)
        #if t2, s2 are empty return inf
        if len(t2) == 0:
            return np.inf
        s2_interp = np.interp(t1,t2,s2)
        distance = np.mean((s1-s2_interp)**2)
        return distance
    if metric == 'log_hazard':
        #calculate the mse between the two survival curves
        t1,h1 = sr1.getHazard()
        t1,h1 = trim_to_range(t1,h1,time_range) if time_range is not None else (t1,h1)
        t2,h2 = sr2.getHazard()
        t2,h2 = trim_to_range(t2,h2,time_range) if time_range is not None else (t2,h2)
        #if t2, s2 are empty return inf
        if len(t2) == 0:
            return np.inf
        t1s,s1 = sr1.getSurvival()
        t1s,s1 = trim_to_range(t1s,s1,time_range) if time_range is not None else (t1s,s1)
        t2s,s2 = sr2.getSurvival()
        t2s,s2 = trim_to_range(t2s,s2,time_range) if time_range is not None else (t2s,s2)
        s1_interp = np.interp(t1,t1s,s1)
        h2_interp = np.interp(t1,t2,h2)
        n_alive = sr1.npeople*s1_interp
        w = np.sqrt(n_alive)
        distance = np.mean(w*((np.log(h1)-np.log(h2_interp))**2))
        return distance
    if metric == 'baysian':
        #if n_bootstrapa is in kwargs use it, otherwise use 1
        dt = kwargs.get('dt',1)
        return baysianDistance(sr1, sr2, time_range=time_range, dt=dt)
    if metric == 'dirichlet' or metric.startswith('dirichlet'):
        dt = kwargs.get('dt',1)
        lambda_smooth = kwargs.get('lambda_smooth',0.5)
        
        # Parse alpha0 from metric if it follows pattern dirichlet###
        alpha0 = None
        if metric.startswith('dirichlet') and len(metric) > 9:  # 'dirichlet' is 9 chars
            try:
                alpha0 = float(metric[9:])  # Extract everything after 'dirichlet'
            except ValueError:
                # If parsing fails, treat as regular 'dirichlet' metric
                alpha0 = None
        
        return baysian_dirichlet_distance(sr1, sr2, time_range=time_range, dt=dt, 
                                         debug=kwargs.get('debug',False), lambda_smooth=lambda_smooth,
                                         sr_bins=kwargs.get('sr_bins', None), alpha0=alpha0)
    if metric.startswith('KS') :
        death_times1 = sr1.death_times
        death_times2 = sr2.death_times
        #check death_times are not empty
        if len(death_times1) == 0 or len(death_times2) == 0:
            distance = np.inf
            p_value = 0
        else:
            ks_result = ks_2samp(death_times1, death_times2)
            distance = ks_result.statistic
            p_value = ks_result.pvalue
        if metric == 'KS_p_value':
            return distance, p_value
    
    if metric == 'KL_divergence':
        #note that the distributions should be non 0  for all values, currently I dont test this which gives nonsensical results
        #I need to add a test for this, maybe take the middle of the distribution...
        bins = np.linspace(0,80,81 )
        p1, bin_edges1 =sr1.get_death_times_distribution(bins=bins)
        p2, bin_edges2 =sr2.get_death_times_distribution(bins=bins)
        distance = entropy(p1,p2)
    else:
        raise ValueError('metric should be KL_divergence')

    
    return distance
